### ISSUE TITLE
panic errors - can't use pokevision cli anymore

### ISSUE THREAD

**Issue by paulo-erichsen** [jacobmarshall/pokevision-cli#14]
I though I'd share this error that has occurred. 

**My System:**
I'm running 1.0.7-rc.3 from linux ubuntu 16.04 and was running it w/ these params:

**The CLI's Parameters I've been using:**

```
./pokevision watch --lat=xxx --lon=-xxx --name=Office --slack --slack-webhook-url=xxx --slack-channel=pokemon_go --forever --ignore=rattata,pidgey,zubat,venonat,paras,ponyta,mankey,geodude --locale=en --range=300
```

It ran fine for a while (30mins), but then it threw the following errors. **Also I can't start the script again because it throws the same errors whenever I try to run it**

```
2016/07/29 14:44:50 notifying bugsnag: interface conversion: interface is nil, not string
panic: interface conversion: interface is nil, not string [recovered]
    panic: interface conversion: interface is nil, not string [recovered]
    panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x8c60e0, 0xc820344440)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/jacobmarshall/pokevision-cli/vendor/github.com/bugsnag/bugsnag-go.AutoNotify(0xc8204c3f00, 0x1, 0x1)
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/vendor/github.com/bugsnag/bugsnag-go/bugsnag.go:52 +0x151
panic(0x8c60e0, 0xc820344440)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli.HandleAction.func1(0xc820139480)
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli/app.go:476 +0x417
panic(0x8c60e0, 0xc820344440)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
main.FetchPokemonsInRegion(0x4045bdfc15ec6bbd, 0xc05c03431d800000, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/fetch_pokemon.go:24 +0x5c3
main.WatchAction(0xc820022f00, 0x0, 0x0)
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/cmd_watch.go:166 +0xe16
reflect.Value.call(0x808fe0, 0xa3f908, 0x13, 0x95d118, 0x4, 0xc8201393e0, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x808fe0, 0xa3f908, 0x13, 0xc8201393e0, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli.HandleAction(0x808fe0, 0xa3f908, 0xc820022f00, 0x0, 0x0)
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli/app.go:485 +0x2ee
github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli.Command.Run(0x962288, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9f05e0, 0x24, 0x0, ...)
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli/command.go:186 +0x1301
github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli.(*App).Run(0xc82012e480, 0xc82000a0c0, 0xc, 0xc, 0x0, 0x0)
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/vendor/github.com/urfave/cli/app.go:239 +0xa9c
main.main()
    /Users/Jacob/Documents/Go/src/github.com/jacobmarshall/pokevision-cli/main.go:34 +0x2be
2016/07/29 14:44:50 notifying bugsnag: interface conversion: interface is nil, not string [recovered]
```

**Comment by cdzombak** [comment]
I started seeing the same error several minutes ago, as did a friend who's running this tool.

**Comment by jmshal** [comment]
Thanks @paulohefagundes, I will take a look shortly.

**Comment by jmshal** [comment]
I just released [1.0.7](https://github.com/jacobmarshall/pokevision-cli/releases/tag/1.0.7), which fixes this issue. The PokéVision API removed a couple of properties from their main endpoint.

This has happened before, so I will look to see whether there's a better solution for keeping the binary's knowledge of the endpoint's schema up to date.

**Comment by jmshal** [comment]
I also had to quickly push [1.0.8](https://github.com/jacobmarshall/pokevision-cli/releases/tag/1.0.8), due to the fact that the PokéVision API does not provide a unique persistent ID for reference between polls.

**Comment by paulo-erichsen** [comment]
awesome, thanks @jacobmarshall!

**Comment by jmshal** [comment]
You're most welcome. I'll keep this issue open for a while, so people don't create dupes if they come here to report it.
